id: IF0B5518A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T22:56:14+00:00'
last_modified: '2022-06-08T10:21:25.715342+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W27917
  title: མཁས་པ་རྣམས་འཇུག་པའི་སྒོ་ཡི་རྣམ་པར་བཤད་པ་རིག་གནས་འཕྲུལ་གྱི་མེ་ལོང
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    8DDC:
      image_group_id: I4519
      title: ''
      total_pages: 612
      order: 1
      base_file: 8DDC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
