id: P009345
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W27917
  title: མཁས་པ་རྣམས་འཇུག་པའི་སྒོ་ཡི་རྣམ་པར་བཤད་པ་རིག་གནས་འཕྲུལ་གྱི་མེ་ལོང
  author: ''
  volumes:
    0cef9001f2194cfb82aabb7a14c5edbc:
      image_group_id: I4519
      title: ''
      volume_number: 1
      total_pages: 612
      base_file: v001.txt
